const shoesArrayToCreate = [
  {
    name: "Adidas Campus Next Gen",
    brand: "adidas",
    availableSizes: [9, 10, 11, 12, 13],
    inStockSizes: [10, 12, 13],
    price: 215,
    inStock: true,
    gender: "men",
  },
  {
    name: "Samba OG Cardboard",
    brand: "adidas",
    availableSizes: [9, 10, 11, 12],
    inStockSizes: [10, 12],
    price: 230,
    inStock: true,
    gender: "men",
  },
  {
    name: "Samba Og Core",
    brand: "adidas",
    availableSizes: [9, 10, 11, 12, 13],
    inStockSizes: [10, 12, 13],
    price: 250,
    inStock: true,
    gender: "men",
  },
  {
    name: "Air Jordan 1 Low Brown",
    brand: "nike",
    availableSizes: [9, 10, 11, 12],
    inStockSizes: [10, 12],
    price: 350,
    inStock: true,
    gender: "men",
  },
  {
    name: "Air Jordan 1 Low Red Black",
    brand: "nike",
    availableSizes: [9, 10, 11, 12, 13],
    inStockSizes: [10, 12, 13],
    price: 350,
    inStock: true,
    gender: "men",
  },
  {
    name: "Air Jordan 1 Mid Black White",
    brand: "nike",
    availableSizes: [7, 8, 9, 10],
    inStockSizes: [7, 8, 10],
    price: 375,
    inStock: true,
    gender: "men",
  },
  {
    name: "Air Jordan 4 Tech White",
    brand: "nike",
    availableSizes: [9, 10, 11, 12, 13],
    inStockSizes: [10, 12, 13],
    price: 400,
    inStock: true,
    gender: "men",
  },
  {
    name: "Nike Renew Lucent",
    brand: "nike",
    availableSizes: [9, 10, 11, 12],
    inStockSizes: [10, 12],
    price: 275,
    inStock: true,
    gender: "men",
  },
  {
    name: "Air Max 1 Luxe Ale",
    brand: "nike",
    availableSizes: [9, 10, 11, 12, 13],
    inStockSizes: [10, 12, 13],
    price: 200,
    inStock: true,
    gender: "men",
  },
  {
    name: "Comme Des Garcons Play",
    brand: "converse",
    availableSizes: [9, 10, 11, 12],
    inStockSizes: [10, 12],
    price: 220,
    inStock: true,
    gender: "men",
  },
  {
    name: "Vans Old Skool Blue Black",
    brand: "vans",
    availableSizes: [9, 10, 11, 12],
    inStockSizes: [10, 12],
    price: 150,
    inStock: true,
    gender: "men",
  },
  {
    name: "Vans Old Skool Misprint",
    brand: "vans",
    availableSizes: [9, 10, 11, 12],
    inStockSizes: [10, 12],
    price: 150,
    inStock: true,
    gender: "men",
  },

  {
    name: "Adidas Campus 00s Ynuk",
    brand: "adidas",
    availableSizes: [7, 8, 9, 10],
    inStockSizes: [7, 8, 10],
    price: 220,
    inStock: true,
    gender: "women",
  },
  {
    name: "adidas3",
    brand: "adidas",
    availableSizes: [7, 8, 9, 10, 11],
    inStockSizes: [7, 8, 10, 11],
    price: 220,
    inStock: true,
    gender: "women",
  },
  {
    name: "Campus Bad Bunny Cloud",
    brand: "adidas",
    availableSizes: [7, 8, 9, 10, 11],
    inStockSizes: [7, 8, 10, 11],
    price: 300,
    inStock: true,
    gender: "women",
  },
  {
    name: "Air Jordan 1 Low Panda",
    brand: "nike",
    availableSizes: [7, 8, 9, 10],
    inStockSizes: [7, 8, 10],
    price: 325,
    inStock: true,
    gender: "women",
  },
  {
    name: "Air Jordan 1 Low Red Black",
    brand: "nike",
    availableSizes: [7, 8, 9, 10, 11],
    inStockSizes: [7, 8, 10, 11],
    price: 330,
    inStock: true,
    gender: "women",
  },
  {
    name: "Air Max Nuaxis",
    brand: "nike",
    availableSizes: [7, 8, 9, 10],
    inStockSizes: [7, 8, 10],
    price: 250,
    inStock: true,
    gender: "women",
  },
  {
    name: "Nike Air Force 1 Pixel",
    brand: "nike",
    availableSizes: [7, 8, 9, 10, 11],
    inStockSizes: [7, 8, 10, 11],
    price: 220,
    inStock: true,
    gender: "women",
  },
  {
    name: "Nike M2k Tekno",
    brand: "nike",
    availableSizes: [7, 8, 9, 10],
    inStockSizes: [7, 8, 10],
    price: 300,
    inStock: true,
    gender: "women",
  },
  {
    name: "Converse Platform Low",
    brand: "converse",
    availableSizes: [7, 8, 9, 10, 11],
    inStockSizes: [7, 8, 10, 11],
    price: 150,
    inStock: true,
    gender: "women",
  },
  {
    name: "Ugg Classic Ultra Mini",
    brand: "ugg",
    availableSizes: [7, 8, 9, 10],
    inStockSizes: [7, 8, 10],
    price: 275,
    inStock: true,
    gender: "women",
  },
  {
    name: "Ugg Disqutte Slipper",
    brand: "ugg",
    availableSizes: [7, 8, 9, 10, 11],
    inStockSizes: [7, 8, 10, 11],
    price: 375,
    inStock: true,
    gender: "women",
  },
  {
    name: "Ugg Goldenstar Strap",
    brand: "ugg",
    availableSizes: [7, 8, 9, 10],
    inStockSizes: [7, 8, 10],
    price: 220,
    inStock: true,
    gender: "women",
  },
  {
    name: "Vans Old Skool Red",
    brand: "vans",
    availableSizes: [7, 8, 9, 10],
    inStockSizes: [7, 8, 10],
    price: 330,
    inStock: true,
    gender: "women",
  },
];

const usersToCreate = [
  {
    name: "user",
    email: "user@example.com",
    password: "user123",
    isAdmin: false,
  },
  {
    name: "admin",
    email: "admin-@example.com",
    password: "admin123",
    isAdmin: true,
  },
];

const storeBranchesToCreate = [
  {
    name: "colman shoe Store",
    address: "המכללה למנהל ראשון לציון",
    rating: 5,
    contactNumber: "0501111111",
    openingHours: "10:00-19:00",
  },
  {
    name: "rehovot shoe Store",
    address: "קניון רחובות",
    rating: 3,
    contactNumber: "0501111111",
    openingHours: "10:00-19:00",
  },
  {
    name: "tel-aviv shoe Store",
    address: "קניון עזריאלי תל אביב",
    rating: 5,
    contactNumber: "0501111111",
    openingHours: "10:00-19:00",
  },
  {
    name: "ramat-gan shoe Store",
    address: "קניון איילון רמת גן",
    rating: 5,
    contactNumber: "0501111111",
    openingHours: "10:00-19:00",
  },
];

module.exports = {
  usersToCreate,
  storeBranchesToCreate,
  shoesArrayToCreate,
};
